<?php
/**
 * Copyright © Appboxo. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/** @var \Appboxo\Connector\Block\Order\PaymentId $block */
?>
<?php if ($block->isShowPaymentIdInAccount()): ?>
    <?php if ($paymentid = $block->getConnector()): ?>
    <div class="block block-order-paymentid um-connector-block">
        <div class="block-content">  
            <div class="block-title">
                <strong><?= $block->escapeHtml(__('Miniprogram Payment ID')) ?></strong>
            </div>
            <div class="box-content">
                <?= $block->getConnectorHtml(); ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>
